services:
  neo4j:
    image: neo4j:5.12
    container_name: neo4j-lab-container
    environment:
      # use uma senha com >= 8 caracteres
      - NEO4J_AUTH=neo4j/SuperSenha123
      # ajuste a variável de aceite de licença
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_dbms_memory_heap_initial__size=3g
      - NEO4J_dbms_memory_heap_max__size=3g
      - NEO4J_dbms_memory_pagecache_size=1g
      # AJUSTAR O VALOR DE dbms.memory.transaction.total.max
      - NEO4J_dbms_memory_transaction_total_max=3g
    ports:
      - "7474:7474"  # Neo4j Browser
      - "7687:7687"  # Bolt protocol
    volumes:
      - /home/barbosa/labs/bases-empresas/extracted:/import  # Mapeia o diretório local para o diretório de importação
      - ./data/neo4j:/data
    deploy:
      resources:
        limits:
          memory: 6g  # Aumente para o valor desejado
        reservations:
          memory: 6g
