services:
  neo4j:
    image: neo4j:5.12
    container_name: neo4j-lab-container
    environment:
      - NEO4J_AUTH=neo4j/test # usuário: neo4j, senha: test
      - NEO4J_ACCEPT_LICENSE_AGreement=yes
    ports:
      - "7474:7474"   # Neo4j Browser
      - "7687:7687"   # Bolt protocol
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/import
      - neo4j_plugins:/plugins

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins: