services:
  neo4j:
    image: neo4j:5.12
    container_name: neo4j-lab-container
    environment:
      - NEO4J_AUTH=neo4j/SuperSenha123
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_PLUGINS=["apoc", "graph-data-science"]
      - NEO4J_server_memory_heap_initial__size=6G
      - NEO4J_server_memory_heap_max__size=6G
      - NEO4J_server_memory_pagecache_size=2G
    ports:
      - "7474:7474"  # Neo4j Browser
      - "7687:7687"  # Bolt protocol
    volumes:
      - ./data/neo4j-lab-container/data:/data
      - /home/barbosa/labs/bases-empresas/extracted:/import  # Mapeia o diretório local para o diretório de importação
    user: '1000'
    group_add:
    - '1000'
    deploy:
      resources:
        limits:
          memory: 8g  # Aumente para o valor desejado
        reservations:
          memory: 8g
