services:
  neo4j:
    image: neo4j:5.12
    container_name: neo4j-lab-container
    environment:
      # use uma senha com >= 8 caracteres
      - NEO4J_AUTH=neo4j/SuperSenha123
      # ajuste a variável de aceite de licença
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    ports:
      - "7474:7474"  # Neo4j Browser
      - "7687:7687"  # Bolt protocol
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - ./data:/import  # Mapeia o diretório local `./data` para o diretório de importação
      - neo4j_plugins:/plugins

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_plugins:
